import type { FormAppearanceSettings } from "../../components/page-def/builder/pageDef";
import type { TemplateCategory, TemplatePreviewTheme } from "./types";

/** Rich marketing & product copy — kept separate from form field definitions. */
export type TemplateCatalogDetails = {
  key: string;
  category: TemplateCategory;
  categoryLabel: string;
  tags: string[];
  useCases: string[];
  idealFor: string[];
  workflow: string[];
  integrations: string[];
  longDescription: string;
  estimatedMinutes: number;
  highlights: string[];
  preview: TemplatePreviewTheme;
  appearance: FormAppearanceSettings;
};

const baseAppearance = {
  borderRadius: "lg" as const,
  submitStyle: "solid" as const,
  inputStyle: "outline" as const,
};

export const TEMPLATE_CATALOG_DETAILS: TemplateCatalogDetails[] = [
  {
    key: "job-application",
    category: "hr",
    categoryLabel: "HR & hiring",
    tags: ["Hiring", "Recruitment", "Careers", "ATS-ready"],
    useCases: [
      "Campus hiring drives and career fairs",
      "Open role applications on your careers page",
      "Employee referral intake with structured data",
    ],
    idealFor: ["HR teams", "Talent acquisition", "Startups scaling hiring"],
    workflow: [
      "Candidate submits profile, role preference, and portfolio links",
      "Recruiters review structured responses in the responses tab",
      "Shortlisted candidates are contacted using captured email & phone",
    ],
    integrations: ["Respondent metadata", "Email & phone capture", "Analytics breakdown"],
    longDescription:
      "A complete hiring intake form with role selection, experience capture, location, portfolio links, and a narrative cover letter. Designed to replace scattered email applications with one polished, mobile-friendly flow.",
    estimatedMinutes: 4,
    highlights: [
      "Portfolio & LinkedIn fields",
      "Joining date selector",
      "Role-specific dropdown with 6 positions",
      "Experience range with helper text",
      "Mobile-optimized layout",
    ],
    preview: {
      gradientStart: "#4f46e5",
      gradientEnd: "#2563eb",
      badge: "Hiring",
      cta: "Submit application",
      fieldRows: [470, 420, 370],
    },
    appearance: {
      ...baseAppearance,
      primaryColor: "#4f46e5",
      backgroundColor: "#eef2ff",
      surfaceColor: "#ffffff",
      textColor: "#0f172a",
    },
  },
  {
    key: "employee-onboarding",
    category: "hr",
    categoryLabel: "HR & hiring",
    tags: ["Onboarding", "HR ops", "Day one", "IT provisioning"],
    useCases: [
      "Pre-boarding paperwork before day one",
      "Equipment and swag requests for new hires",
      "Manager and department routing for HRIS entry",
    ],
    idealFor: ["People ops", "IT onboarding", "Mid-size companies"],
    workflow: [
      "New hire completes personal and role details",
      "HR receives structured data for payroll and access provisioning",
      "IT uses equipment preference to prepare the laptop bundle",
    ],
    integrations: ["Department routing", "Equipment preferences", "Dietary notes for events"],
    longDescription:
      "Streamline day-one logistics with a checklist-style intake covering legal name, start date, reporting manager, laptop preference, and welcome-event accommodations.",
    estimatedMinutes: 3,
    highlights: [
      "Department routing across 7 teams",
      "Laptop preference selector",
      "Manager assignment field",
      "T-shirt size for welcome kit",
      "Dietary & accessibility notes",
    ],
    preview: {
      gradientStart: "#1d4ed8",
      gradientEnd: "#6366f1",
      badge: "Onboarding",
      cta: "Complete intake",
      fieldRows: [460, 430, 390],
    },
    appearance: {
      ...baseAppearance,
      primaryColor: "#1d4ed8",
      backgroundColor: "#eff6ff",
      surfaceColor: "#ffffff",
      textColor: "#0f172a",
      inputStyle: "filled",
    },
  },
  {
    key: "lead-capture",
    category: "sales",
    categoryLabel: "Sales & marketing",
    tags: ["B2B", "Inbound", "Qualification", "Demo requests"],
    useCases: [
      "Website demo request forms",
      "Pricing and enterprise inquiry pages",
      "Partner and affiliate referral intake",
    ],
    idealFor: ["Sales teams", "Growth marketers", "SaaS founders"],
    workflow: [
      "Prospect shares firmographics and buying timeline",
      "Marketing scores leads by team size, industry, and budget",
      "Sales follows up with a tailored demo or proposal",
    ],
    integrations: ["UTM metadata", "Email domain analytics", "Audience insights"],
    longDescription:
      "Qualify inbound demand with firmographic fields, budget signals, industry segmentation, and a free-text goals section — everything your SDR needs before the first call.",
    estimatedMinutes: 3,
    highlights: [
      "Budget & timeline qualifiers",
      "Industry segmentation",
      "Team size dropdown",
      "Company website capture",
      "Buying intent scoring fields",
    ],
    preview: {
      gradientStart: "#b45309",
      gradientEnd: "#f59e0b",
      badge: "Sales",
      cta: "Request demo",
      fieldRows: [465, 430, 385],
    },
    appearance: {
      ...baseAppearance,
      primaryColor: "#b45309",
      backgroundColor: "#fffbeb",
      surfaceColor: "#ffffff",
      textColor: "#1c1917",
      submitStyle: "outline",
    },
  },
  {
    key: "event-registration",
    category: "events",
    categoryLabel: "Events",
    tags: ["Conferences", "Webinars", "Meetups", "Ticketing"],
    useCases: [
      "Conference and summit registration",
      "Workshop and masterclass sign-ups",
      "VIP guest lists with dietary requirements",
    ],
    idealFor: ["Event organizers", "Community teams", "Marketing events"],
    workflow: [
      "Attendee selects ticket tier and session track",
      "Organizer exports responses for badge printing and catering",
      "Special requirements are flagged for on-site accommodations",
    ],
    integrations: ["Device & locale metadata", "Email domain breakdown", "Response analytics"],
    longDescription:
      "Purpose-built for live and virtual events — capture attendee contact info, ticket type, organization, session interests, dietary needs, and accessibility requests in one branded form.",
    estimatedMinutes: 3,
    highlights: [
      "5 ticket tiers including Early Bird & VIP",
      "Dietary preference selector",
      "Session track selection",
      "Organization & job title fields",
      "Accessibility & plus-one notes",
    ],
    preview: {
      gradientStart: "#7c3aed",
      gradientEnd: "#ec4899",
      badge: "Events",
      cta: "Reserve spot",
      fieldRows: [460, 420, 400],
    },
    appearance: {
      ...baseAppearance,
      primaryColor: "#7c3aed",
      backgroundColor: "#f5f3ff",
      surfaceColor: "#ffffff",
      textColor: "#1e1b4b",
    },
  },
  {
    key: "customer-support-request",
    category: "support",
    categoryLabel: "Customer support",
    tags: ["Helpdesk", "Ticketing", "SaaS", "Bug reports"],
    useCases: [
      "In-app support widget intake",
      "Billing and account access escalations",
      "Structured bug reports with reproduction steps",
    ],
    idealFor: ["Support teams", "Customer success", "SaaS products"],
    workflow: [
      "Customer describes the issue with product context and priority",
      "Ticket is routed by category and product area",
      "Agent uses device environment and expected-behavior fields to reproduce",
    ],
    integrations: ["Priority routing fields", "Metadata capture", "Top-text answer analytics"],
    longDescription:
      "Replace vague support emails with a structured ticket form featuring product area tagging, priority levels, device environment, issue narrative, and expected-behavior comparison.",
    estimatedMinutes: 4,
    highlights: [
      "Priority & category routing",
      "Product area tagging",
      "Device / browser selector",
      "Expected vs actual behavior fields",
      "Account ID for faster lookup",
    ],
    preview: {
      gradientStart: "#0f766e",
      gradientEnd: "#0ea5e9",
      badge: "Support",
      cta: "Open ticket",
      fieldRows: [470, 440, 390],
    },
    appearance: {
      ...baseAppearance,
      primaryColor: "#0d9488",
      backgroundColor: "#ecfdf5",
      surfaceColor: "#ffffff",
      textColor: "#0f172a",
      submitStyle: "soft",
      inputStyle: "filled",
    },
  },
  {
    key: "patient-intake",
    category: "healthcare",
    categoryLabel: "Healthcare",
    tags: ["Clinic", "Intake", "Telehealth", "Patient portal"],
    useCases: [
      "First-time patient registration",
      "Pre-visit telehealth intake",
      "Specialist referral preparation",
    ],
    idealFor: ["Clinics", "Telehealth providers", "Dental & specialty practices"],
    workflow: [
      "Patient completes demographics and visit reason before arrival",
      "Front desk reviews intake and insurance details",
      "Clinician reads symptom narrative and medical history in advance",
    ],
    integrations: ["Phone & email capture", "Respondent attributes", "Completion rate tracking"],
    longDescription:
      "A thoughtful first-visit intake covering demographics, emergency contact, insurance, visit type, current symptoms, and medical history — reducing waiting-room paperwork.",
    estimatedMinutes: 5,
    highlights: [
      "Emergency contact capture",
      "Insurance provider field",
      "Symptom narrative with prompts",
      "Visit type selector",
      "Medical history & allergies section",
    ],
    preview: {
      gradientStart: "#0f766e",
      gradientEnd: "#16a34a",
      badge: "Healthcare",
      cta: "Submit intake",
      fieldRows: [450, 430, 380],
    },
    appearance: {
      ...baseAppearance,
      primaryColor: "#0f766e",
      backgroundColor: "#ecfdf5",
      surfaceColor: "#ffffff",
      textColor: "#0f172a",
      borderRadius: "md",
      submitStyle: "soft",
      inputStyle: "filled",
    },
  },
  {
    key: "product-feedback",
    category: "product",
    categoryLabel: "Product feedback",
    tags: ["NPS", "CSAT", "Roadmap", "Voice of customer"],
    useCases: [
      "Post-release satisfaction surveys",
      "Beta program feedback collection",
      "Churn exit interviews",
    ],
    idealFor: ["Product managers", "UX researchers", "Customer success"],
    workflow: [
      "User rates likelihood to recommend and overall satisfaction",
      "Product team segments feedback by primary use case",
      "Feature requests feed into roadmap prioritization",
    ],
    integrations: ["NPS distribution analytics", "Text answer breakdown", "Device type insights"],
    longDescription:
      "Measure product-market fit with an NPS scale, satisfaction ladder, favorite-feature capture, improvement-area selector, and open-ended feature requests.",
    estimatedMinutes: 2,
    highlights: [
      "0–10 NPS recommend scale",
      "5-point satisfaction ladder",
      "Primary use case segmentation",
      "Improvement area selector",
      "Open feature request field",
    ],
    preview: {
      gradientStart: "#db2777",
      gradientEnd: "#8b5cf6",
      badge: "Feedback",
      cta: "Share feedback",
      fieldRows: [455, 415, 375],
    },
    appearance: {
      ...baseAppearance,
      primaryColor: "#db2777",
      backgroundColor: "#fdf2f8",
      surfaceColor: "#ffffff",
      textColor: "#1f2937",
    },
  },
  {
    key: "course-enrollment",
    category: "education",
    categoryLabel: "Education",
    tags: ["LMS", "Bootcamp", "Cohort", "Training"],
    useCases: [
      "Online course enrollment",
      "Bootcamp cohort placement",
      "Corporate training sign-ups",
    ],
    idealFor: ["Ed-tech platforms", "Bootcamps", "Corporate L&D teams"],
    workflow: [
      "Student selects course and declares skill level",
      "Admissions reviews learning goals and format preference",
      "Cohort is assigned based on skill and availability",
    ],
    integrations: ["Referral source tracking", "Email capture", "Question analytics"],
    longDescription:
      "Enrollment form for courses and bootcamps with skill-level assessment, format preference, learning goals narrative, and referral attribution.",
    estimatedMinutes: 3,
    highlights: [
      "5 course options",
      "Skill level assessment",
      "Live / self-paced / hybrid selector",
      "Learning goals narrative",
      "Referral source attribution",
    ],
    preview: {
      gradientStart: "#0369a1",
      gradientEnd: "#22d3ee",
      badge: "Education",
      cta: "Enroll now",
      fieldRows: [450, 425, 395],
    },
    appearance: {
      ...baseAppearance,
      primaryColor: "#0369a1",
      backgroundColor: "#f0f9ff",
      surfaceColor: "#ffffff",
      textColor: "#0c4a6e",
    },
  },

  {
    key: "contact-us",
    category: "general",
    categoryLabel: "General",
    tags: ["Contact", "Website", "Inquiry"],
    useCases: ["Website contact page", "Landing page footer form", "General inbox routing"],
    idealFor: ["Startups", "Agencies", "Small businesses"],
    workflow: [
      "Visitor selects inquiry type and writes their message",
      "Form routes to sales, support, or general inbox",
      "Team replies using captured email or phone preference",
    ],
    integrations: ["Email capture", "Inquiry categorization", "Response analytics"],
    longDescription:
      "A versatile contact form with inquiry type routing, subject line, detailed message body, and preferred contact method — perfect for any website.",
    estimatedMinutes: 2,
    highlights: ["Inquiry type routing", "Subject + message fields", "Preferred contact method", "Optional phone capture"],
    preview: { gradientStart: "#475569", gradientEnd: "#94a3b8", badge: "Contact", cta: "Send message", fieldRows: [460, 420, 380] },
    appearance: { ...baseAppearance, primaryColor: "#475569", backgroundColor: "#f8fafc", surfaceColor: "#ffffff", textColor: "#0f172a" },
  },
  {
    key: "newsletter-signup",
    category: "general",
    categoryLabel: "General",
    tags: ["Newsletter", "Email list", "Marketing"],
    useCases: ["Blog sidebar signup", "Product launch waitlist", "Content marketing list"],
    idealFor: ["Content teams", "Marketers", "Indie creators"],
    workflow: ["Visitor shares email and interests", "Marketing segments by topic preference", "Automated welcome sequence triggers"],
    integrations: ["Email capture", "Interest segmentation", "Referral source tracking"],
    longDescription: "Minimal-friction newsletter signup with interest tags, frequency preference, and attribution — built for list growth without overwhelming subscribers.",
    estimatedMinutes: 1,
    highlights: ["Interest-based segmentation", "Frequency preference", "Optional company field", "Referral attribution"],
    preview: { gradientStart: "#0ea5e9", gradientEnd: "#38bdf8", badge: "Subscribe", cta: "Join newsletter", fieldRows: [440, 400, 360] },
    appearance: { ...baseAppearance, primaryColor: "#0ea5e9", backgroundColor: "#f0f9ff", surfaceColor: "#ffffff", textColor: "#0c4a6e", borderRadius: "lg" },
  },
  {
    key: "restaurant-reservation",
    category: "hospitality",
    categoryLabel: "Hospitality",
    tags: ["Restaurant", "Booking", "F&B"],
    useCases: ["Restaurant table reservations", "Special occasion bookings", "Private dining requests"],
    idealFor: ["Restaurants", "Cafés", "Catering teams"],
    workflow: ["Guest picks date, time, and party size", "Host reviews seating and occasion notes", "Confirmation sent via phone or email"],
    integrations: ["Phone capture", "Occasion tagging", "Special request notes"],
    longDescription: "Table booking form with party size, time slots, seating preferences, occasion type, and allergy or celebration notes.",
    estimatedMinutes: 2,
    highlights: ["Time slot selector", "Party size field", "Seating preferences", "Occasion tagging", "Special requests"],
    preview: { gradientStart: "#c2410c", gradientEnd: "#fb923c", badge: "Dining", cta: "Book table", fieldRows: [455, 415, 375] },
    appearance: { ...baseAppearance, primaryColor: "#c2410c", backgroundColor: "#fff7ed", surfaceColor: "#ffffff", textColor: "#431407", submitStyle: "soft" },
  },
  {
    key: "webinar-registration",
    category: "events",
    categoryLabel: "Events",
    tags: ["Webinar", "Virtual event", "B2B"],
    useCases: ["Product webinar sign-ups", "Live demo registration", "Office hours enrollment"],
    idealFor: ["Marketing teams", "SaaS companies", "Community managers"],
    workflow: ["Attendee registers for a session slot", "Marketing sends calendar invite and reminders", "Host reviews pre-submitted questions"],
    integrations: ["Work email capture", "Session selection", "Reminder preferences"],
    longDescription: "B2B webinar registration with session picker, experience level, pre-submitted questions, and email reminder preferences.",
    estimatedMinutes: 2,
    highlights: ["Multi-session picker", "Job title & company capture", "Pre-submitted questions", "Reminder preferences"],
    preview: { gradientStart: "#6d28d9", gradientEnd: "#a78bfa", badge: "Webinar", cta: "Register free", fieldRows: [450, 410, 370] },
    appearance: { ...baseAppearance, primaryColor: "#6d28d9", backgroundColor: "#f5f3ff", surfaceColor: "#ffffff", textColor: "#1e1b4b" },
  },
  {
    key: "volunteer-signup",
    category: "events",
    categoryLabel: "Events",
    tags: ["Volunteer", "Nonprofit", "Community"],
    useCases: ["Conference volunteer recruitment", "Charity event staffing", "Community program signup"],
    idealFor: ["Nonprofits", "Event organizers", "Community groups"],
    workflow: ["Volunteer selects role and availability", "Coordinator matches skills to shifts", "Emergency contact on file for event day"],
    integrations: ["Role preference capture", "Skills free-text", "Emergency contact"],
    longDescription: "Recruit event volunteers with role preferences, availability windows, skills, and emergency contact information.",
    estimatedMinutes: 3,
    highlights: ["5 volunteer role options", "Availability selector", "Skills narrative", "Emergency contact required"],
    preview: { gradientStart: "#059669", gradientEnd: "#34d399", badge: "Volunteer", cta: "Sign up", fieldRows: [450, 420, 390] },
    appearance: { ...baseAppearance, primaryColor: "#059669", backgroundColor: "#ecfdf5", surfaceColor: "#ffffff", textColor: "#064e3b", inputStyle: "filled" },
  },
  {
    key: "exit-interview",
    category: "hr",
    categoryLabel: "HR & hiring",
    tags: ["Offboarding", "Retention", "Culture"],
    useCases: ["Resignation exit interviews", "Contract-end feedback", "Retention analysis"],
    idealFor: ["HR teams", "People ops", "Leadership"],
    workflow: ["Departing employee submits confidential feedback", "HR aggregates themes across exits", "Leadership acts on retention insights"],
    integrations: ["Reason-for-leaving analytics", "NPS-style recommend score", "Text answer breakdown"],
    longDescription: "Structured exit interview capturing departure reasons, overall experience rating, recommend score, and open feedback on what worked and what didn't.",
    estimatedMinutes: 5,
    highlights: ["Departure reason selector", "Recommend employer score", "What worked / improve fields", "Department context"],
    preview: { gradientStart: "#4338ca", gradientEnd: "#818cf8", badge: "Exit", cta: "Submit feedback", fieldRows: [460, 430, 400] },
    appearance: { ...baseAppearance, primaryColor: "#4338ca", backgroundColor: "#eef2ff", surfaceColor: "#ffffff", textColor: "#1e1b4b", submitStyle: "soft" },
  },
  {
    key: "real-estate-inquiry",
    category: "sales",
    categoryLabel: "Sales & marketing",
    tags: ["Real estate", "Property", "Leads"],
    useCases: ["Buyer lead capture", "Rental inquiries", "Property listing interest"],
    idealFor: ["Real estate agents", "Property portals", "Developers"],
    workflow: ["Prospect shares intent, budget, and location", "Agent matches to available listings", "Follow-up call scheduled based on timeline"],
    integrations: ["Budget segmentation", "Intent type tracking", "Location capture"],
    longDescription: "Property inquiry form with buy/rent/sell intent, property type, budget range, preferred location, move timeline, and must-have requirements.",
    estimatedMinutes: 3,
    highlights: ["Buy / rent / sell intent", "Budget range in INR", "Location preference", "Move timeline", "Must-haves narrative"],
    preview: { gradientStart: "#15803d", gradientEnd: "#4ade80", badge: "Property", cta: "Get callback", fieldRows: [465, 425, 385] },
    appearance: { ...baseAppearance, primaryColor: "#15803d", backgroundColor: "#f0fdf4", surfaceColor: "#ffffff", textColor: "#14532d" },
  },
  {
    key: "client-project-brief",
    category: "sales",
    categoryLabel: "Sales & marketing",
    tags: ["Agency", "Scoping", "Proposal"],
    useCases: ["Agency new-business intake", "Freelancer project inquiry", "RFP pre-qualification"],
    idealFor: ["Agencies", "Consultancies", "Freelancers"],
    workflow: ["Client describes project type, budget, and timeline", "Agency reviews goals and reference links", "Scoped proposal sent within SLA"],
    integrations: ["Budget qualification", "Timeline signals", "Goals narrative analytics"],
    longDescription: "Agency-ready project brief with type, budget, timeline, success goals, and reference links — everything needed before a discovery call.",
    estimatedMinutes: 4,
    highlights: ["6 project type options", "Budget & timeline qualifiers", "Goals narrative", "Reference links field"],
    preview: { gradientStart: "#7c2d12", gradientEnd: "#ea580c", badge: "Brief", cta: "Start project", fieldRows: [455, 420, 380] },
    appearance: { ...baseAppearance, primaryColor: "#ea580c", backgroundColor: "#fff7ed", surfaceColor: "#ffffff", textColor: "#431407", submitStyle: "outline" },
  },
  {
    key: "it-helpdesk-request",
    category: "operations",
    categoryLabel: "Operations & IT",
    tags: ["IT", "Internal", "Helpdesk"],
    useCases: ["Employee IT support tickets", "Access provisioning requests", "Hardware replacement intake"],
    idealFor: ["IT teams", "Internal ops", "Growing companies"],
    workflow: ["Employee files categorized request with urgency", "IT triages by category and device type", "Resolution tracked via ticket metadata"],
    integrations: ["Urgency routing", "Device type capture", "Category analytics"],
    longDescription: "Internal IT ticketing with request category, urgency levels, device type, issue summary, and detailed troubleshooting notes.",
    estimatedMinutes: 3,
    highlights: ["6 request categories", "4-tier urgency scale", "Device type selector", "Summary + detail fields"],
    preview: { gradientStart: "#0891b2", gradientEnd: "#22d3ee", badge: "IT", cta: "Submit ticket", fieldRows: [470, 440, 400] },
    appearance: { ...baseAppearance, primaryColor: "#0891b2", backgroundColor: "#ecfeff", surfaceColor: "#ffffff", textColor: "#164e63", inputStyle: "filled" },
  },
  {
    key: "bug-report",
    category: "product",
    categoryLabel: "Product feedback",
    tags: ["Engineering", "QA", "Defect"],
    useCases: ["Internal bug reporting", "Beta tester defect intake", "QA regression logging"],
    idealFor: ["Engineering teams", "QA", "Beta programs"],
    workflow: ["Reporter files severity, area, and reproduction steps", "Engineering triages by severity and environment", "Fix verified against expected behavior notes"],
    integrations: ["Severity breakdown", "Environment tagging", "Affected area analytics"],
    longDescription: "Engineering-grade bug report with severity, affected area, build version, environment, reproduction steps, and expected behavior.",
    estimatedMinutes: 4,
    highlights: ["4-tier severity scale", "7 affected areas", "Environment selector", "Reproduction steps", "Expected behavior"],
    preview: { gradientStart: "#dc2626", gradientEnd: "#f87171", badge: "Bug", cta: "Report bug", fieldRows: [460, 430, 390] },
    appearance: { ...baseAppearance, primaryColor: "#dc2626", backgroundColor: "#fef2f2", surfaceColor: "#ffffff", textColor: "#450a0a" },
  },
  {
    key: "appointment-request",
    category: "healthcare",
    categoryLabel: "Healthcare",
    tags: ["Clinic", "Scheduling", "Telehealth"],
    useCases: ["Clinic appointment booking", "Telehealth scheduling", "Follow-up visit requests"],
    idealFor: ["Clinics", "Dental practices", "Telehealth providers"],
    workflow: ["Patient requests type, date, and time preference", "Front desk confirms slot and patient status", "Clinician receives reason-for-visit summary"],
    integrations: ["Appointment type analytics", "New vs returning segmentation", "Phone capture"],
    longDescription: "Medical appointment request with visit type, preferred date and time window, new/returning patient status, and reason for visit.",
    estimatedMinutes: 2,
    highlights: ["5 appointment types", "Time window preference", "New vs returning patient", "Reason for visit narrative"],
    preview: { gradientStart: "#047857", gradientEnd: "#6ee7b7", badge: "Clinic", cta: "Request slot", fieldRows: [450, 420, 380] },
    appearance: { ...baseAppearance, primaryColor: "#047857", backgroundColor: "#ecfdf5", surfaceColor: "#ffffff", textColor: "#064e3b", borderRadius: "md", inputStyle: "filled" },
  },
  {
    key: "scholarship-application",
    category: "education",
    categoryLabel: "Education",
    tags: ["Scholarship", "Financial aid", "Admissions"],
    useCases: ["University scholarship intake", "Grant applications", "Merit award screening"],
    idealFor: ["Universities", "Foundations", "Ed-tech platforms"],
    workflow: ["Student submits academic info and personal statement", "Review committee scores by scholarship type", "Shortlisted applicants contacted for interview"],
    integrations: ["GPA capture", "Scholarship type segmentation", "Personal statement analytics"],
    longDescription: "Scholarship application with institution, program level, GPA, scholarship type, personal statement, and optional financial need narrative.",
    estimatedMinutes: 6,
    highlights: ["Merit & need-based types", "GPA / percentage field", "Personal statement", "Financial need optional field"],
    preview: { gradientStart: "#1e40af", gradientEnd: "#60a5fa", badge: "Scholarship", cta: "Apply now", fieldRows: [455, 425, 395] },
    appearance: { ...baseAppearance, primaryColor: "#1e40af", backgroundColor: "#eff6ff", surfaceColor: "#ffffff", textColor: "#1e3a8a" },
  },
];

export const TEMPLATE_CATALOG_DETAILS_BY_KEY = Object.fromEntries(
  TEMPLATE_CATALOG_DETAILS.map((entry) => [entry.key, entry]),
);
