import type { PageDef } from "../page-def";

export const TEMPLATE_DEFINITIONS: Record<string, PageDef> = {
  "job-application": {
    id: "job-application",
    title: "Job Application Form",
    description:
      "Collect candidate details, role preferences, and portfolio links in a polished hiring flow.",
    components: [
      {
        id: "candidateName",
        type: "TextAnswerInput",
        label: "Full Name",
        required: true,
        placeholder: "Aarav Sharma",
      },
      {
        id: "candidateEmail",
        type: "EmailAnswerInput",
        label: "Email Address",
        required: true,
        placeholder: "aarav@email.com",
      },
      {
        id: "candidatePhone",
        type: "PhoneAnswerInput",
        label: "Phone Number",
        required: true,
        placeholder: "+91 98765 43210",
      },
      {
        id: "positionApplied",
        type: "SelectAnswerInput",
        label: "Position Applied For",
        options: [
          "Frontend Developer",
          "Backend Developer",
          "Full Stack Engineer",
          "UI/UX Designer",
          "Product Manager",
          "Data Analyst",
        ],
        required: true,
      },
      {
        id: "yearsOfExperience",
        type: "NumberAnswerInput",
        label: "Years of Experience",
        min: 0,
        max: 40,
        helperText: "Include internships and freelance work if relevant.",
      },
      {
        id: "currentLocation",
        type: "TextAnswerInput",
        label: "Current City",
        placeholder: "Bengaluru, India",
      },
      {
        id: "linkedinUrl",
        type: "TextAnswerInput",
        label: "LinkedIn Profile",
        placeholder: "https://linkedin.com/in/your-profile",
      },
      {
        id: "portfolioUrl",
        type: "TextAnswerInput",
        label: "Portfolio / GitHub",
        placeholder: "https://github.com/your-handle",
      },
      {
        id: "availability",
        type: "SelectAnswerInput",
        label: "Earliest Joining Date",
        options: ["Immediately", "Within 2 weeks", "Within 1 month", "Within 3 months"],
      },
      {
        id: "coverLetter",
        type: "DescriptionAnswerInput",
        label: "Why do you want to join us?",
        helperText: "Share what excites you about the role and your relevant experience.",
        rows: 5,
      },
    ],
  },

  "customer-support-request": {
    id: "customer-support-request",
    title: "Customer Support Request",
    description:
      "Structured intake for support teams with priority routing, product context, and reproduction steps.",
    components: [
      {
        id: "customerName",
        type: "TextAnswerInput",
        label: "Customer Name",
        required: true,
        placeholder: "Priya Nair",
      },
      {
        id: "customerEmail",
        type: "EmailAnswerInput",
        label: "Customer Email",
        required: true,
        placeholder: "priya@company.com",
      },
      {
        id: "accountId",
        type: "TextAnswerInput",
        label: "Account ID",
        placeholder: "ACC-20481",
        helperText: "Optional — helps us locate your account faster.",
      },
      {
        id: "productArea",
        type: "SelectAnswerInput",
        label: "Product Area",
        options: ["Billing", "Dashboard", "Integrations", "Mobile App", "API", "Other"],
        required: true,
      },
      {
        id: "issueCategory",
        type: "SelectAnswerInput",
        label: "Issue Category",
        options: [
          "Billing",
          "Technical Problem",
          "Account Access",
          "Feature Request",
          "Data / Privacy",
          "Other",
        ],
        required: true,
      },
      {
        id: "priority",
        type: "SelectAnswerInput",
        label: "Priority",
        options: ["Low", "Medium", "High", "Critical"],
        required: true,
      },
      {
        id: "deviceEnvironment",
        type: "SelectAnswerInput",
        label: "Device / Browser",
        options: ["Chrome (Desktop)", "Safari (Desktop)", "Mobile App", "Other"],
      },
      {
        id: "issueDescription",
        type: "DescriptionAnswerInput",
        label: "Issue Description",
        helperText: "What happened? Include exact steps and any error messages.",
        rows: 6,
        required: true,
      },
      {
        id: "expectedBehavior",
        type: "DescriptionAnswerInput",
        label: "Expected Behavior",
        helperText: "What did you expect to happen instead?",
        rows: 3,
      },
    ],
  },

  "event-registration": {
    id: "event-registration",
    title: "Event Registration Form",
    description:
      "Registration for conferences, workshops, and meetups with ticketing and accessibility needs.",
    components: [
      {
        id: "attendeeName",
        type: "TextAnswerInput",
        label: "Attendee Name",
        required: true,
        placeholder: "Mia Wilson",
      },
      {
        id: "attendeeEmail",
        type: "EmailAnswerInput",
        label: "Attendee Email",
        required: true,
        placeholder: "mia@company.com",
      },
      {
        id: "attendeePhone",
        type: "PhoneAnswerInput",
        label: "Attendee Phone",
        placeholder: "+91 90000 12345",
      },
      {
        id: "ticketType",
        type: "SelectAnswerInput",
        label: "Ticket Type",
        options: ["General", "Standard", "Early Bird", "VIP", "Student"],
        required: true,
      },
      {
        id: "organization",
        type: "TextAnswerInput",
        label: "Organization / Company",
        placeholder: "Acme Corp",
      },
      {
        id: "jobTitle",
        type: "TextAnswerInput",
        label: "Job Title",
        placeholder: "Product Designer",
      },
      {
        id: "sessionInterest",
        type: "SelectAnswerInput",
        label: "Primary Track",
        options: ["Keynotes", "Workshops", "Networking", "Expo Hall"],
      },
      {
        id: "dietaryPreference",
        type: "SelectAnswerInput",
        label: "Dietary Preference",
        options: ["No preference", "Vegetarian", "Vegan", "Halal", "Gluten free"],
      },
      {
        id: "specialRequirements",
        type: "DescriptionAnswerInput",
        label: "Special Requirements",
        helperText: "Accessibility, seating, plus-one, or other requests.",
        rows: 4,
      },
    ],
  },

  "patient-intake": {
    id: "patient-intake",
    title: "Patient Intake Form",
    description:
      "First-visit intake for clinics with demographics, visit reason, and medical history.",
    components: [
      {
        id: "patientName",
        type: "TextAnswerInput",
        label: "Patient Full Name",
        required: true,
        placeholder: "Rahul Mehta",
      },
      {
        id: "patientEmail",
        type: "EmailAnswerInput",
        label: "Email Address",
        placeholder: "rahul@email.com",
      },
      {
        id: "patientPhone",
        type: "PhoneAnswerInput",
        label: "Phone Number",
        required: true,
        placeholder: "+91 98765 43210",
      },
      {
        id: "dateOfBirth",
        type: "TextAnswerInput",
        label: "Date of Birth",
        placeholder: "DD/MM/YYYY",
        required: true,
      },
      {
        id: "gender",
        type: "SelectAnswerInput",
        label: "Gender",
        options: ["Female", "Male", "Non-binary", "Prefer not to say"],
      },
      {
        id: "emergencyContact",
        type: "TextAnswerInput",
        label: "Emergency Contact",
        placeholder: "Name and phone number",
        required: true,
      },
      {
        id: "visitType",
        type: "SelectAnswerInput",
        label: "Visit Type",
        options: [
          "General Consultation",
          "Follow-up",
          "Lab Report Review",
          "Vaccination",
          "Emergency",
        ],
        required: true,
      },
      {
        id: "insuranceProvider",
        type: "TextAnswerInput",
        label: "Insurance Provider",
        placeholder: "Provider name and policy number",
      },
      {
        id: "currentSymptoms",
        type: "DescriptionAnswerInput",
        label: "Current Symptoms",
        helperText: "When did they start? Severity on a day-to-day basis?",
        rows: 4,
        required: true,
      },
      {
        id: "medicalHistory",
        type: "DescriptionAnswerInput",
        label: "Medical History & Allergies",
        helperText: "Chronic conditions, surgeries, medications, and known allergies.",
        rows: 5,
      },
    ],
  },

  "lead-capture": {
    id: "lead-capture",
    title: "Sales Lead Capture Form",
    description:
      "Qualify inbound leads with firmographics, budget signals, and buying timeline.",
    components: [
      {
        id: "leadName",
        type: "TextAnswerInput",
        label: "Contact Name",
        required: true,
        placeholder: "Ananya Nair",
      },
      {
        id: "workEmail",
        type: "EmailAnswerInput",
        label: "Work Email",
        required: true,
        placeholder: "ananya@company.com",
      },
      {
        id: "jobTitle",
        type: "TextAnswerInput",
        label: "Job Title",
        placeholder: "Head of Operations",
      },
      {
        id: "companyName",
        type: "TextAnswerInput",
        label: "Company Name",
        required: true,
        placeholder: "Northwind Labs",
      },
      {
        id: "companyWebsite",
        type: "TextAnswerInput",
        label: "Company Website",
        placeholder: "https://company.com",
      },
      {
        id: "teamSize",
        type: "SelectAnswerInput",
        label: "Team Size",
        options: ["1-10", "11-50", "51-200", "201-1000", "1000+"],
        required: true,
      },
      {
        id: "industry",
        type: "SelectAnswerInput",
        label: "Industry",
        options: ["SaaS", "E-commerce", "Healthcare", "Finance", "Education", "Other"],
      },
      {
        id: "budgetRange",
        type: "SelectAnswerInput",
        label: "Budget Range (USD)",
        options: ["< 1,000", "1,000 - 5,000", "5,001 - 20,000", "20,000+"],
      },
      {
        id: "timeline",
        type: "SelectAnswerInput",
        label: "Buying Timeline",
        options: ["This month", "1-3 months", "3-6 months", "Just researching"],
        required: true,
      },
      {
        id: "requirements",
        type: "DescriptionAnswerInput",
        label: "What are you trying to solve?",
        helperText: "Goals, current tools, and success criteria for the next quarter.",
        rows: 5,
      },
    ],
  },

  "product-feedback": {
    id: "product-feedback",
    title: "Product Feedback Survey",
    description:
      "Capture NPS, satisfaction drivers, and feature requests after a product release.",
    components: [
      {
        id: "respondentName",
        type: "TextAnswerInput",
        label: "Your Name",
        placeholder: "Optional",
      },
      {
        id: "respondentEmail",
        type: "EmailAnswerInput",
        label: "Email",
        placeholder: "we@company.com",
        helperText: "Optional — only if you'd like a follow-up.",
      },
      {
        id: "npsScore",
        type: "SelectAnswerInput",
        label: "How likely are you to recommend us?",
        options: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
        required: true,
        helperText: "0 = not at all likely, 10 = extremely likely",
      },
      {
        id: "primaryUseCase",
        type: "SelectAnswerInput",
        label: "Primary Use Case",
        options: ["Form building", "Team collaboration", "Analytics", "Integrations", "Other"],
        required: true,
      },
      {
        id: "satisfaction",
        type: "SelectAnswerInput",
        label: "Overall Satisfaction",
        options: ["Very dissatisfied", "Dissatisfied", "Neutral", "Satisfied", "Very satisfied"],
        required: true,
      },
      {
        id: "favoriteFeature",
        type: "TextAnswerInput",
        label: "Favorite Feature",
        placeholder: "What do you love most?",
      },
      {
        id: "improvementArea",
        type: "SelectAnswerInput",
        label: "Biggest Improvement Area",
        options: ["Speed", "Design", "Reporting", "Mobile experience", "Documentation", "Pricing"],
      },
      {
        id: "featureRequest",
        type: "DescriptionAnswerInput",
        label: "Feature Request",
        helperText: "What would make this product indispensable for you?",
        rows: 4,
      },
    ],
  },

  "employee-onboarding": {
    id: "employee-onboarding",
    title: "Employee Onboarding Checklist",
    description:
      "Day-one intake for HR with personal details, equipment needs, and policy acknowledgements.",
    components: [
      {
        id: "employeeName",
        type: "TextAnswerInput",
        label: "Full Legal Name",
        required: true,
      },
      {
        id: "personalEmail",
        type: "EmailAnswerInput",
        label: "Personal Email",
        required: true,
      },
      {
        id: "workEmail",
        type: "EmailAnswerInput",
        label: "Work Email",
        placeholder: "name@company.com",
      },
      {
        id: "startDate",
        type: "TextAnswerInput",
        label: "Start Date",
        placeholder: "DD/MM/YYYY",
        required: true,
      },
      {
        id: "department",
        type: "SelectAnswerInput",
        label: "Department",
        options: ["Engineering", "Design", "Sales", "Marketing", "Operations", "HR", "Finance"],
        required: true,
      },
      {
        id: "managerName",
        type: "TextAnswerInput",
        label: "Reporting Manager",
        required: true,
      },
      {
        id: "equipmentPreference",
        type: "SelectAnswerInput",
        label: "Laptop Preference",
        options: ["MacBook Pro 14\"", "MacBook Air", "Windows Laptop", "Linux Workstation"],
        required: true,
      },
      {
        id: "tshirtSize",
        type: "SelectAnswerInput",
        label: "T-Shirt Size",
        options: ["XS", "S", "M", "L", "XL", "XXL"],
      },
      {
        id: "dietaryNotes",
        type: "DescriptionAnswerInput",
        label: "Dietary / Accessibility Notes",
        helperText: "For welcome lunch and workplace accommodations.",
        rows: 3,
      },
    ],
  },

  "course-enrollment": {
    id: "course-enrollment",
    title: "Course Enrollment Form",
    description:
      "Enrollment for online or in-person courses with skill level and learning goals.",
    components: [
      {
        id: "studentName",
        type: "TextAnswerInput",
        label: "Student Name",
        required: true,
      },
      {
        id: "studentEmail",
        type: "EmailAnswerInput",
        label: "Email Address",
        required: true,
      },
      {
        id: "studentPhone",
        type: "PhoneAnswerInput",
        label: "Phone Number",
      },
      {
        id: "courseSelection",
        type: "SelectAnswerInput",
        label: "Course",
        options: [
          "UI/UX Fundamentals",
          "React for Beginners",
          "Advanced TypeScript",
          "Data Analytics Bootcamp",
          "Product Management 101",
        ],
        required: true,
      },
      {
        id: "skillLevel",
        type: "SelectAnswerInput",
        label: "Current Skill Level",
        options: ["Beginner", "Intermediate", "Advanced"],
        required: true,
      },
      {
        id: "learningFormat",
        type: "SelectAnswerInput",
        label: "Preferred Format",
        options: ["Live online", "Self-paced", "In-person", "Hybrid"],
        required: true,
      },
      {
        id: "learningGoals",
        type: "DescriptionAnswerInput",
        label: "Learning Goals",
        helperText: "What do you want to achieve by the end of this course?",
        rows: 4,
        required: true,
      },
      {
        id: "referralSource",
        type: "SelectAnswerInput",
        label: "How did you hear about us?",
        options: ["Friend / colleague", "LinkedIn", "Google search", "Newsletter", "Other"],
      },
    ],
  },

  "contact-us": {
    id: "contact-us",
    title: "Contact Us Form",
    description: "General-purpose contact form for websites, landing pages, and support inboxes.",
    components: [
      { id: "fullName", type: "TextAnswerInput", label: "Full Name", required: true, placeholder: "Jane Doe" },
      { id: "email", type: "EmailAnswerInput", label: "Email Address", required: true },
      { id: "phone", type: "PhoneAnswerInput", label: "Phone Number", placeholder: "Optional" },
      {
        id: "inquiryType",
        type: "SelectAnswerInput",
        label: "How can we help?",
        options: ["General question", "Sales inquiry", "Partnership", "Press / media", "Other"],
        required: true,
      },
      {
        id: "subject",
        type: "TextAnswerInput",
        label: "Subject",
        required: true,
        placeholder: "Brief summary of your message",
      },
      {
        id: "message",
        type: "DescriptionAnswerInput",
        label: "Message",
        helperText: "Share as much detail as you can — we'll route this to the right team.",
        rows: 6,
        required: true,
      },
      {
        id: "preferredContact",
        type: "SelectAnswerInput",
        label: "Preferred contact method",
        options: ["Email", "Phone", "Either"],
      },
    ],
  },

  "newsletter-signup": {
    id: "newsletter-signup",
    title: "Newsletter Signup",
    description: "Lightweight list-building form with interests and consent-friendly fields.",
    components: [
      { id: "firstName", type: "TextAnswerInput", label: "First Name", required: true },
      { id: "email", type: "EmailAnswerInput", label: "Email Address", required: true },
      {
        id: "interests",
        type: "SelectAnswerInput",
        label: "Primary interest",
        options: ["Product updates", "Industry news", "Tutorials", "Events", "Deals & offers"],
        required: true,
      },
      {
        id: "frequency",
        type: "SelectAnswerInput",
        label: "Email frequency",
        options: ["Weekly digest", "Monthly roundup", "Only major announcements"],
      },
      { id: "company", type: "TextAnswerInput", label: "Company (optional)" },
      {
        id: "referralSource",
        type: "SelectAnswerInput",
        label: "How did you find us?",
        options: ["Search engine", "Social media", "Friend", "Blog / article", "Other"],
      },
    ],
  },

  "restaurant-reservation": {
    id: "restaurant-reservation",
    title: "Restaurant Reservation",
    description: "Table booking with party size, timing, and special occasion details.",
    components: [
      { id: "guestName", type: "TextAnswerInput", label: "Guest Name", required: true },
      { id: "guestPhone", type: "PhoneAnswerInput", label: "Phone Number", required: true },
      { id: "guestEmail", type: "EmailAnswerInput", label: "Email Address" },
      { id: "reservationDate", type: "TextAnswerInput", label: "Preferred Date", placeholder: "DD/MM/YYYY", required: true },
      {
        id: "reservationTime",
        type: "SelectAnswerInput",
        label: "Preferred Time",
        options: ["12:00 PM", "1:00 PM", "7:00 PM", "7:30 PM", "8:00 PM", "8:30 PM", "9:00 PM"],
        required: true,
      },
      {
        id: "partySize",
        type: "NumberAnswerInput",
        label: "Party Size",
        min: 1,
        max: 20,
        required: true,
      },
      {
        id: "seatingPreference",
        type: "SelectAnswerInput",
        label: "Seating Preference",
        options: ["No preference", "Indoor", "Outdoor", "Private booth", "High chair needed"],
      },
      {
        id: "occasion",
        type: "SelectAnswerInput",
        label: "Occasion",
        options: ["Casual dining", "Birthday", "Anniversary", "Business meal", "Celebration"],
      },
      {
        id: "specialRequests",
        type: "DescriptionAnswerInput",
        label: "Special Requests",
        helperText: "Allergies, accessibility, or celebration notes.",
        rows: 3,
      },
    ],
  },

  "webinar-registration": {
    id: "webinar-registration",
    title: "Webinar Registration",
    description: "Sign up for live webinars with role context and reminder preferences.",
    components: [
      { id: "attendeeName", type: "TextAnswerInput", label: "Full Name", required: true },
      { id: "workEmail", type: "EmailAnswerInput", label: "Work Email", required: true },
      { id: "jobTitle", type: "TextAnswerInput", label: "Job Title", required: true },
      { id: "company", type: "TextAnswerInput", label: "Company", required: true },
      {
        id: "webinarSession",
        type: "SelectAnswerInput",
        label: "Webinar Session",
        options: ["Product demo — Tue 11 AM", "Best practices — Thu 4 PM", "Q&A office hours — Fri 10 AM"],
        required: true,
      },
      {
        id: "experienceLevel",
        type: "SelectAnswerInput",
        label: "Experience Level",
        options: ["New to the topic", "Some experience", "Advanced practitioner"],
        required: true,
      },
      {
        id: "questionsForHost",
        type: "DescriptionAnswerInput",
        label: "Questions for the host",
        helperText: "Submit questions in advance so we can cover them live.",
        rows: 3,
      },
      {
        id: "reminderPreference",
        type: "SelectAnswerInput",
        label: "Reminder preference",
        options: ["Email 1 day before", "Email 1 hour before", "Both", "No reminders"],
      },
    ],
  },

  "volunteer-signup": {
    id: "volunteer-signup",
    title: "Volunteer Signup Form",
    description: "Recruit volunteers with availability, skills, and emergency contact info.",
    components: [
      { id: "volunteerName", type: "TextAnswerInput", label: "Full Name", required: true },
      { id: "volunteerEmail", type: "EmailAnswerInput", label: "Email", required: true },
      { id: "volunteerPhone", type: "PhoneAnswerInput", label: "Phone", required: true },
      {
        id: "volunteerRole",
        type: "SelectAnswerInput",
        label: "Preferred Role",
        options: ["Registration desk", "Logistics", "Speaker support", "Social media", "General help"],
        required: true,
      },
      {
        id: "availability",
        type: "SelectAnswerInput",
        label: "Availability",
        options: ["Weekday mornings", "Weekday evenings", "Weekends", "Flexible"],
        required: true,
      },
      {
        id: "priorExperience",
        type: "SelectAnswerInput",
        label: "Prior volunteer experience",
        options: ["None", "Some", "Experienced volunteer"],
      },
      {
        id: "skills",
        type: "DescriptionAnswerInput",
        label: "Relevant skills",
        helperText: "Languages, first-aid, AV setup, design, etc.",
        rows: 3,
      },
      { id: "emergencyContact", type: "TextAnswerInput", label: "Emergency Contact", required: true },
    ],
  },

  "exit-interview": {
    id: "exit-interview",
    title: "Employee Exit Interview",
    description: "Confidential offboarding feedback to improve retention and culture.",
    components: [
      { id: "employeeName", type: "TextAnswerInput", label: "Your Name", required: true },
      { id: "department", type: "TextAnswerInput", label: "Department", required: true },
      { id: "lastDay", type: "TextAnswerInput", label: "Last Working Day", placeholder: "DD/MM/YYYY", required: true },
      {
        id: "reasonForLeaving",
        type: "SelectAnswerInput",
        label: "Primary reason for leaving",
        options: ["New opportunity", "Compensation", "Management", "Work-life balance", "Relocation", "Personal reasons", "Other"],
        required: true,
      },
      {
        id: "overallExperience",
        type: "SelectAnswerInput",
        label: "Overall experience",
        options: ["Excellent", "Good", "Average", "Below average", "Poor"],
        required: true,
      },
      {
        id: "wouldRecommend",
        type: "SelectAnswerInput",
        label: "Would you recommend this company?",
        options: ["Definitely", "Probably", "Not sure", "Probably not", "Definitely not"],
        required: true,
      },
      {
        id: "whatWorkedWell",
        type: "DescriptionAnswerInput",
        label: "What worked well?",
        rows: 4,
        required: true,
      },
      {
        id: "whatCouldImprove",
        type: "DescriptionAnswerInput",
        label: "What could we improve?",
        rows: 4,
        required: true,
      },
    ],
  },

  "real-estate-inquiry": {
    id: "real-estate-inquiry",
    title: "Real Estate Inquiry",
    description: "Capture buyer or renter intent with budget, timeline, and property preferences.",
    components: [
      { id: "clientName", type: "TextAnswerInput", label: "Full Name", required: true },
      { id: "clientEmail", type: "EmailAnswerInput", label: "Email", required: true },
      { id: "clientPhone", type: "PhoneAnswerInput", label: "Phone", required: true },
      {
        id: "intentType",
        type: "SelectAnswerInput",
        label: "Looking to",
        options: ["Buy", "Rent", "Sell", "Invest"],
        required: true,
      },
      {
        id: "propertyType",
        type: "SelectAnswerInput",
        label: "Property Type",
        options: ["Apartment", "Villa", "Plot", "Commercial", "Office space"],
        required: true,
      },
      {
        id: "budgetRange",
        type: "SelectAnswerInput",
        label: "Budget Range (INR)",
        options: ["< 50 L", "50 L – 1 Cr", "1 – 2 Cr", "2 – 5 Cr", "5 Cr+"],
        required: true,
      },
      {
        id: "preferredLocation",
        type: "TextAnswerInput",
        label: "Preferred Location",
        placeholder: "Neighbourhood or city",
        required: true,
      },
      {
        id: "moveTimeline",
        type: "SelectAnswerInput",
        label: "Move Timeline",
        options: ["Immediately", "1–3 months", "3–6 months", "Just exploring"],
      },
      {
        id: "additionalRequirements",
        type: "DescriptionAnswerInput",
        label: "Must-haves",
        helperText: "BHK, parking, amenities, proximity to schools, etc.",
        rows: 4,
      },
    ],
  },

  "client-project-brief": {
    id: "client-project-brief",
    title: "Client Project Brief",
    description: "Agency intake for scoping design, dev, or marketing engagements.",
    components: [
      { id: "contactName", type: "TextAnswerInput", label: "Contact Name", required: true },
      { id: "contactEmail", type: "EmailAnswerInput", label: "Email", required: true },
      { id: "companyName", type: "TextAnswerInput", label: "Company", required: true },
      {
        id: "projectType",
        type: "SelectAnswerInput",
        label: "Project Type",
        options: ["Website redesign", "Mobile app", "Branding", "Marketing campaign", "Consulting", "Other"],
        required: true,
      },
      {
        id: "budgetRange",
        type: "SelectAnswerInput",
        label: "Estimated Budget",
        options: ["< ₹2 L", "₹2 – 5 L", "₹5 – 15 L", "₹15 L+", "Not sure yet"],
        required: true,
      },
      {
        id: "timeline",
        type: "SelectAnswerInput",
        label: "Desired Timeline",
        options: ["ASAP", "1–2 months", "3–6 months", "Flexible"],
        required: true,
      },
      {
        id: "projectGoals",
        type: "DescriptionAnswerInput",
        label: "Project Goals",
        helperText: "What success looks like in 6–12 months.",
        rows: 4,
        required: true,
      },
      {
        id: "referenceLinks",
        type: "DescriptionAnswerInput",
        label: "Reference Links",
        helperText: "Competitors, inspiration, or existing assets.",
        rows: 3,
      },
    ],
  },

  "it-helpdesk-request": {
    id: "it-helpdesk-request",
    title: "IT Helpdesk Request",
    description: "Internal IT ticket form for access, hardware, and software issues.",
    components: [
      { id: "employeeName", type: "TextAnswerInput", label: "Employee Name", required: true },
      { id: "employeeEmail", type: "EmailAnswerInput", label: "Work Email", required: true },
      { id: "employeeId", type: "TextAnswerInput", label: "Employee ID" },
      {
        id: "requestCategory",
        type: "SelectAnswerInput",
        label: "Request Category",
        options: ["Password reset", "VPN / network", "New software", "Hardware issue", "Access request", "Other"],
        required: true,
      },
      {
        id: "urgency",
        type: "SelectAnswerInput",
        label: "Urgency",
        options: ["Low — can wait", "Medium — today", "High — blocking work", "Critical — system down"],
        required: true,
      },
      {
        id: "deviceType",
        type: "SelectAnswerInput",
        label: "Device",
        options: ["MacBook", "Windows laptop", "Mobile phone", "Monitor / peripheral", "Other"],
      },
      {
        id: "issueSummary",
        type: "TextAnswerInput",
        label: "Issue Summary",
        required: true,
        placeholder: "One-line description",
      },
      {
        id: "issueDetails",
        type: "DescriptionAnswerInput",
        label: "Details & steps tried",
        rows: 5,
        required: true,
      },
    ],
  },

  "bug-report": {
    id: "bug-report",
    title: "Bug Report Form",
    description: "Engineering bug intake with severity, environment, and reproduction steps.",
    components: [
      { id: "reporterName", type: "TextAnswerInput", label: "Reporter Name", required: true },
      { id: "reporterEmail", type: "EmailAnswerInput", label: "Email", required: true },
      {
        id: "severity",
        type: "SelectAnswerInput",
        label: "Severity",
        options: ["Critical — production down", "High — major feature broken", "Medium — workaround exists", "Low — cosmetic"],
        required: true,
      },
      {
        id: "affectedArea",
        type: "SelectAnswerInput",
        label: "Affected Area",
        options: ["Authentication", "Dashboard", "Forms", "API", "Mobile", "Billing", "Other"],
        required: true,
      },
      { id: "appVersion", type: "TextAnswerInput", label: "App / Build Version", placeholder: "e.g. v2.4.1" },
      {
        id: "environment",
        type: "SelectAnswerInput",
        label: "Environment",
        options: ["Production", "Staging", "Local dev"],
        required: true,
      },
      {
        id: "stepsToReproduce",
        type: "DescriptionAnswerInput",
        label: "Steps to Reproduce",
        rows: 5,
        required: true,
      },
      {
        id: "expectedBehavior",
        type: "DescriptionAnswerInput",
        label: "Expected Behavior",
        rows: 3,
        required: true,
      },
    ],
  },

  "appointment-request": {
    id: "appointment-request",
    title: "Medical Appointment Request",
    description: "Schedule clinic visits with preferred times and reason for appointment.",
    components: [
      { id: "patientName", type: "TextAnswerInput", label: "Patient Name", required: true },
      { id: "patientPhone", type: "PhoneAnswerInput", label: "Phone Number", required: true },
      { id: "patientEmail", type: "EmailAnswerInput", label: "Email" },
      {
        id: "appointmentType",
        type: "SelectAnswerInput",
        label: "Appointment Type",
        options: ["General check-up", "Follow-up visit", "Specialist referral", "Lab results review", "Vaccination"],
        required: true,
      },
      {
        id: "preferredDate",
        type: "TextAnswerInput",
        label: "Preferred Date",
        placeholder: "DD/MM/YYYY",
        required: true,
      },
      {
        id: "preferredTime",
        type: "SelectAnswerInput",
        label: "Preferred Time",
        options: ["Morning (9–12)", "Afternoon (12–4)", "Evening (4–7)", "Any"],
        required: true,
      },
      {
        id: "isNewPatient",
        type: "SelectAnswerInput",
        label: "Patient Status",
        options: ["New patient", "Returning patient"],
        required: true,
      },
      {
        id: "reasonForVisit",
        type: "DescriptionAnswerInput",
        label: "Reason for Visit",
        rows: 4,
        required: true,
      },
    ],
  },

  "scholarship-application": {
    id: "scholarship-application",
    title: "Scholarship Application",
    description: "Student financial aid intake with academic info and personal statement.",
    components: [
      { id: "applicantName", type: "TextAnswerInput", label: "Full Name", required: true },
      { id: "applicantEmail", type: "EmailAnswerInput", label: "Email", required: true },
      { id: "applicantPhone", type: "PhoneAnswerInput", label: "Phone", required: true },
      { id: "institution", type: "TextAnswerInput", label: "School / University", required: true },
      {
        id: "program",
        type: "SelectAnswerInput",
        label: "Program",
        options: ["Undergraduate", "Postgraduate", "PhD", "Diploma / certificate"],
        required: true,
      },
      {
        id: "gpa",
        type: "NumberAnswerInput",
        label: "GPA / Percentage",
        min: 0,
        max: 100,
        helperText: "Enter percentage if GPA scale differs.",
      },
      {
        id: "scholarshipType",
        type: "SelectAnswerInput",
        label: "Scholarship Type",
        options: ["Merit-based", "Need-based", "Sports", "Research", "Diversity & inclusion"],
        required: true,
      },
      {
        id: "personalStatement",
        type: "DescriptionAnswerInput",
        label: "Personal Statement",
        helperText: "Why you deserve this scholarship and your future goals.",
        rows: 6,
        required: true,
      },
      {
        id: "financialNeed",
        type: "DescriptionAnswerInput",
        label: "Financial Need (optional)",
        rows: 3,
      },
    ],
  },
};
